export interface BoardLineItem {
  artist: string;
  songName: string;
  placement: number;
}

export interface Board {
  name: string;
  lines: Array<BoardLineItem>
}

export const animals: Board = {
  name: 'Animals - Die 100 besten Lieder mit Tieren',
  lines: [
    { placement: 1, songName: "I Wanna Be Your Dog", artist: "Iggy & The Stooges" },
    { placement: 2, songName: "The Lovecats", artist: "The Cure" },
    { placement: 3, songName: "Blackbird", artist: "The Beatles" },
    { placement: 4, songName: "When Doves Cry", artist: "Prince & The Revolution" },
    { placement: 5, songName: "Rock Lobster", artist: "The B-52's" },
    { placement: 6, songName: "Wild Horses", artist: "The Rollling Stones" },
    { placement: 7, songName: "Black Dog", artist: "Led Zeppelin" },
    { placement: 8, songName: "A Horse With No Name", artist: "America" },
    { placement: 9, songName: "I Am The Walrus", artist: "The Beatles" },
    { placement: 10, songName: "Monkey Gone To Heaven", artist: "Pixies" },
    { placement: 11, songName: "Dog Days Are Over", artist: "Florence + The Machine" },
    { placement: 12, songName: "Nellie The Elephant", artist: "Toy Dolls" },
    { placement: 13, songName: "Statdtaffe", artist: "Peter Fox" },
    { placement: 14, songName: "Eisbär", artist: "Grauzone" },
    { placement: 15, songName: "Elephant", artist: "Tame Impala" },
    { placement: 16, songName: "Buffalo Stance", artist: "Neneh Cherry" },
    { placement: 17, songName: "Eye Of The Tiger", artist: "Survivor" },
    { placement: 18, songName: "Hounds Of Love", artist: "Kate Bush" },
    { placement: 19, songName: "Barracuda", artist: "Heart" },
    { placement: 20, songName: "Claudia Hat 'Nen Schäferhund", artist: "Die Ärzte" },
    { placement: 21, songName: "Hungry Like The Wolf", artist: "Duran Duran" },
    { placement: 22, songName: "Human Fly", artist: "The Cramps" },
    { placement: 23, songName: "Cat People (Putting Out Fire)", artist: "David Bowie" },
    { placement: 24, songName: "Bird On The Wire", artist: "Leonard Cohen" },
    { placement: 25, songName: "Can Your Pussy Do The Dog?", artist: "The Cramps" },
    { placement: 26, songName: "I Like Birds", artist: "Eels" },
    { placement: 27, songName: "Albatros", artist: "Karat" },
    { placement: 28, songName: "Meat Is Murder", artist: "The Smiths" },
    { placement: 29, songName: "Die Tse Tse Fliege", artist: "Oma Hans" },
    { placement: 30, songName: "White Rabbit", artist: "Jefferson Airplane" },
    { placement: 31, songName: "The Lion Sleeps Tonight", artist: "The Tokens" },
    { placement: 32, songName: "Walkin’ My Cat Named Dog", artist: "Norma Tanega" },
    { placement: 33, songName: "Who Let The Dogs Out?", artist: "Baha Men" },
    { placement: 34, songName: "I’m Like A Bird", artist: "Nelly Furtado" },
    { placement: 35, songName: "Boris The Spider", artist: "The Who" },
    { placement: 36, songName: "Surfin' Bird", artist: "The Trashmen" },
    { placement: 37, songName: "Fly Like An Eagle", artist: "Steve Miller Band" },
    { placement: 38, songName: "Hound Dog", artist: "Elvis Presley" },
    { placement: 39, songName: "Katzeklo", artist: "Helge Schneider" },
    { placement: 40, songName: "Die Tiere Sind Unruhig", artist: "Kante" },
    { placement: 41, songName: "Stray Cat Strut", artist: "Stray Cats" },
    { placement: 42, songName: "Wolf Like Me", artist: "TV On The Radio" },
    { placement: 43, songName: "Crocodile Rock", artist: "Elton John" },
    { placement: 44, songName: "Cats And Dogs", artist: "Gorilla Biscuits" },
    { placement: 45, songName: "Endlich Einmal", artist: "Tomte" },
    { placement: 46, songName: "Shock The Monkey", artist: "Peter Gabriel" },
    { placement: 47, songName: "Zum Laichen Und Sterben Ziehen Die Lachse Den Fluss Hinauf", artist: "Thees Uhlmann" },
    { placement: 48, songName: "Animal", artist: "Pearl Jam" },
    { placement: 49, songName: "Schwan", artist: "Turbostaat" },
    { placement: 50, songName: "White Bird", artist: "It`s A Beautiful Day" },
    { placement: 51, songName: "Karl Der Käfer", artist: "Gänsehaut" },
    { placement: 52, songName: "Little Lion Man", artist: "Mumford & Sons" },
    { placement: 53, songName: "Fox On The Run", artist: "The Sweet" },
    { placement: 54, songName: "Animal", artist: "Miike Snow" },
    { placement: 55, songName: "Ride A White Swan", artist: "T. Rex" },
    { placement: 56, songName: "Hund", artist: "Yukno" },
    { placement: 57, songName: "Bird Song", artist: "Lene Lovich" },
    { placement: 58, songName: "Horse And I", artist: "Bat For Lashes" },
    { placement: 59, songName: "I Cut Like A Buffalo", artist: "The Dead Weather" },
    { placement: 60, songName: "Brass Monkey", artist: "Beastie Boys" },
    { placement: 61, songName: "Three Little Birds", artist: "Bob Marley & The Wailers" },
    { placement: 62, songName: "Coyote", artist: "Joni Mitchell" },
    { placement: 63, songName: "Hound Dog", artist: "Big Mama Thornton" },
    { placement: 64, songName: "The Lamb Lies Down On Broadway", artist: "Genesis" },
    { placement: 65, songName: "Piggies", artist: "The Beatles" },
    { placement: 66, songName: "Buffalo Soldier", artist: "Bob Marley & The Wailers\n" },
    { placement: 67, songName: "Land: Horses / Land Of A Thousand Dances / La Mer(de)", artist: "Patti Smith" },
    { placement: 68, songName: "Eagle", artist: "ABBA" },
    { placement: 69, songName: "Teach Me Tiger", artist: "April Stevens" },
    { placement: 70, songName: "Atomic Dog", artist: "George Clinton" },
    { placement: 71, songName: "Birds", artist: "Frida Hyvönen" },
    { placement: 72, songName: "I Love My Dog", artist: "Cat Stevens" },
    { placement: 73, songName: "Karma Chameleon", artist: "Culture Club" },
    { placement: 74, songName: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 75, songName: "Octopus‘s Garden", artist: "The Beatles" },
    { placement: 76, songName: "Sheep", artist: "The Housemartins" },
    { placement: 77, songName: "Do The Dog", artist: "The Specials" },
    { placement: 78, songName: "The Fox In The Snow", artist: "Belle And Sebastian" },
    { placement: 79, songName: "Albatross", artist: "Fleetwood Mac" },
    { placement: 80, songName: "Crickets Sing For Anamaria", artist: "Marcos Valle" },
    { placement: 81, songName: "N' Käfer Auf'm Blatt", artist: "Chicorée" },
    { placement: 82, songName: "Mister, Would You Please Help My Pony?", artist: "Ween" },
    { placement: 83, songName: "Ich Und Mein Freund Die Katze", artist: "Interzone" },
    { placement: 84, songName: "Iron Lion Zion", artist: "Bob Marley" },
    { placement: 85, songName: "(Let Me Be Your) Teddy Bear", artist: "Elvis Presley" },
    { placement: 86, songName: "Pink Panther Theme", artist: "Henry Mancini" },
    { placement: 87, songName: "Sparrow", artist: "Marvin Gaye" },
    { placement: 88, songName: "The Snake", artist: "Al Wilson" },
    { placement: 89, songName: "Der Letzte Kranich", artist: "Tocotronic" },
    { placement: 90, songName: "Free Bird", artist: "Lynyrd Skynyrd" },
    { placement: 91, songName: "Rhinoceros", artist: "The Smashing Pumpkins" },
    { placement: 92, songName: "Me And My Monkey", artist: "Robbie Williams" },
    { placement: 93, songName: "We Are The Pigs", artist: "Suede" },
    { placement: 94, songName: "Too Many Puppies", artist: "Primus" },
    { placement: 95, songName: "Sheep", artist: "Pink Floyd" },
    { placement: 96, songName: "Long Snake Moan", artist: "PJ Harvey" },
    { placement: 97, songName: "Lullaby", artist: "The Cure" },
    { placement: 98, songName: "Pet Sematary", artist: "Ramones" },
    { placement: 99, songName: "Delilah", artist: "Queen" },
    { placement: 100, songName: "Anaconda", artist: "Nicki Minaj" }]
};

export const numbers: Board = {
  name: 'Magic Numbers - Die 100 besten Songs mit Zahlen im Titel',
  lines: [
    { placement: 1, songName: "Song 2", artist: "Blur" },
    { placement: 2, songName: "1234", artist: "Feist" },
    { placement: 3, songName: "1999", artist: "Prince" },
    { placement: 4, songName: "Seven Nation Army", artist: "The White Stripes" },
    { placement: 5, songName: "50 Ways To Leave Your Lover", artist: "Paul Simon" },
    { placement: 6, songName: "One", artist: "U2" },
    { placement: 7, songName: "Disco 2000", artist: "Pulp" },
    { placement: 8, songName: "1979", artist: "The Smashing Pumpkins" },
    { placement: 9, songName: "99 Problems", artist: "Jay-Z" },
    { placement: 10, songName: "One", artist: "Metallica" },
    { placement: 11, songName: "99 Luftballons", artist: "Nena" },
    { placement: 12, songName: "Edge Of Seventeen", artist: "Stevie Nicks" },
    { placement: 13, songName: "48 Crash", artist: "Suzi Quatro" },
    { placement: 14, songName: "54-46 Was My Number", artist: "Toots & The Maytals" },
    { placement: 15, songName: "1969", artist: "The Stooges" },
    { placement: 16, songName: "2000 Light Years From Home", artist: "The Rolling Stones" },
    { placement: 17, songName: "10.15 Saturday Night", artist: "The Cure" },
    { placement: 18, songName: "96 Tears", artist: "? & The Mysterians" },
    { placement: 19, songName: "Eight Days A Week", artist: "The Beatles" },
    { placement: 20, songName: "20th Century Boy", artist: "T. Rex" },
    { placement: 21, songName: "100%", artist: "Sonic Youth" },
    { placement: 22, songName: "Thirteen", artist: "Big Star" },
    { placement: 23, songName: "2-4-6-8 Motorway", artist: "Tom Robinson Band" },
    { placement: 24, songName: "6060-842", artist: "The B-52's" },
    { placement: 25, songName: "Nummern", artist: "Kraftwerk" },
    { placement: 26, songName: "Five Years", artist: "David Bowie" },
    { placement: 27, songName: "Nothing Compares 2 U", artist: "Sinéad O' Connor" },
    { placement: 28, songName: "Eight Miles High\n", artist: "The Byrds\n" },
    { placement: 29, songName: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
    { placement: 30, songName: "12:15", artist: "The Strokes" },
    { placement: 31, songName: "The Magic Number", artist: "De La Soul" },
    { placement: 32, songName: "If 6 Was 9", artist: "The Jimi Hendrix Experience" },
    { placement: 33, songName: "7 Seconds", artist: "Youssou N`Dour & Neneh Cherry" },
    { placement: 34, songName: "12XU", artist: "Wire" },
    { placement: 35, songName: "When I'm Sixty-Four", artist: "The Beatles" },
    { placement: 36, songName: "One", artist: "Aimee Mann" },
    { placement: 37, songName: "The Four Horsemen", artist: "Aphrodite`s Child" },
    { placement: 38, songName: "The Number Of The Beast", artist: "Iron Maiden" },
    { placement: 39, songName: "2000 Mädchen", artist: "Die Ärzte" },
    { placement: 40, songName: "Three Is A Magic Number", artist: "Bob Dorough" },
    { placement: 41, songName: "48 Stunden", artist: "Kettcar" },
    { placement: 42, songName: "19", artist: "Paul Hardcastle" },
    { placement: 43, songName: "Four Women", artist: "Nina Simone" },
    { placement: 44, songName: "1901", artist: "Phoenix" },
    { placement: 45, songName: "Little 15", artist: "Depeche Mode" },
    { placement: 46, songName: "Little Numbers", artist: "Boy" },
    { placement: 47, songName: "9 To 5", artist: "Dolly Parton" },
    { placement: 48, songName: "911 Is A Joke", artist: "Public Enemy" },
    { placement: 49, songName: "Waltz #2 (XO)", artist: "Elliott Smith" },
    { placement: 50, songName: "Thirteen", artist: "Jingo De Lunch" },
    { placement: 51, songName: "Highway 61 Revisited", artist: "Bob Dylan" },
    { placement: 52, songName: "50ft Queenie", artist: "PJ Harvey" },
    { placement: 53, songName: "One", artist: "Harry Nilsson" },
    { placement: 54, songName: "Tausend Tränen Tief", artist: "Blumfeld" },
    { placement: 55, songName: "21st Century (Digital Boy)", artist: "Bad Religion" },
    { placement: 56, songName: "Seventeen", artist: "Sharon Van Etten" },
    { placement: 57, songName: "2 Oder 3 Dinge, Die Ich Von Dir Weiß", artist: "Blumfeld" },
    { placement: 58, songName: "Zehn", artist: "Farin Urlaub Racing Team" },
    { placement: 59, songName: "Eins Und Eins, Das Macht Zwei", artist: "Hildegard Knef" },
    { placement: 60, songName: "Paris 1919", artist: "John Cale" },
    { placement: 61, songName: "51st State", artist: "New Model Army" },
    { placement: 62, songName: "Two Weeks", artist: "FKA Twigs" },
    { placement: 63, songName: "Five To One", artist: "The Doors" },
    { placement: 64, songName: "52 Girls", artist: "The B-52's" },
    { placement: 65, songName: "Nr. 48", artist: "Engerling" },
    { placement: 66, songName: "One More Time", artist: "Daft Punk" },
    { placement: 67, songName: "25 Or 6 To 4", artist: "Chicago" },
    { placement: 68, songName: "54/40 Or Fight", artist: "Dead Moon" },
    { placement: 69, songName: "The Magnificent Seven", artist: "The Clash" },
    { placement: 70, songName: "Chelsea Hotel #2", artist: "Leonard Cohen" },
    { placement: 71, songName: "Take Five", artist: "Dave Brubeck Quartet" },
    { placement: 72, songName: "Revolution 9", artist: "The Beatles" },
    { placement: 73, songName: "One", artist: "Three Dog Night" },
    { placement: 74, songName: "Forty Six & 2", artist: "Tool" },
    { placement: 75, songName: "1/2 Lovesong", artist: "Die Ärzte" },
    { placement: 76, songName: "Seventeen Seconds", artist: "The Cure" },
    { placement: 77, songName: "Thirteen\n", artist: "Johnny Cash" },
    { placement: 78, songName: "1,2,3,4", artist: "Wanda" },
    { placement: 79, songName: "2 Become 1", artist: "Spice Girls" },
    { placement: 80, songName: "3 Millionen", artist: "Bosse" },
    { placement: 81, songName: "33 \"GOD\"", artist: "Bon Iver" },
    { placement: 82, songName: "1000 Und 1 Nacht (Zoom!)", artist: "Klaus Lage Band" },
    { placement: 83, songName: "Summer Of `69", artist: "Bryan Adams" },
    { placement: 84, songName: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, songName: "Route 66", artist: "Chuck Berry" },
    { placement: 86, songName: "9010", artist: "Kummer" },
    { placement: 87, songName: "23", artist: "Jimmy Eat World" },
    { placement: 88, songName: "I-94", artist: "Radio Birdman" },
    { placement: 89, songName: "Chant No. 1 (I Don't Need This Pressure On)", artist: "Spandau Ballet" },
    { placement: 90, songName: "Mit 66 Jahren", artist: "Udo Jürgens" },
    { placement: 91, songName: "Perfect 10", artist: "The Beautiful South" },
    { placement: 92, songName: "Nineteen Hunderd And Eighty Five", artist: "Paul McCartney & Wings" },
    { placement: 93, songName: "3 MC's And 1 DJ", artist: "Beastie Boys" },
    { placement: 94, songName: "Links 2-3-4", artist: "Rammstein" },
    { placement: 95, songName: "One", artist: "Johnny Cash" },
    { placement: 96, songName: "Care Of Cell 44", artist: "The Zombies" },
    { placement: 97, songName: "1-2 5", artist: "The Haunted" },
    { placement: 98, songName: "19th Nervous Breakdown", artist: "The Rolling Stones" },
    { placement: 99, songName: "'39", artist: "Queen" },
    { placement: 100, songName: "4 Degrees", artist: "Anohni" }]
};

export const family: Board = {
  name: 'We Are Family - Die 100 besten Familienlieder',
  lines: [
    { placement: 1, songName: "Family Affair", artist: "Sly & The Family Stone" },
    { placement: 2, songName: "Father And Son", artist: "Cat Stevens" },
    { placement: 3, songName: "We Are Family", artist: "Sister Sledge" },
    { placement: 4, songName: "Mother", artist: "Danzig" },
    { placement: 5, songName: "We're A Happy Family", artist: "Ramones" },
    { placement: 6, songName: "Mother", artist: "John Lennon & Plastic Ono Band" },
    { placement: 7, songName: "Sisters Are Doin' It For Themselves", artist: "Eurythmics & Aretha Franklin" },
    { placement: 8, songName: "Papa Was A Rollin' Stone", artist: "The Temptations" },
    { placement: 9, songName: "Family Affair", artist: "Mary J. Blige" },
    { placement: 10, songName: "Father Figure", artist: "George Michael" },
    { placement: 11, songName: "My Little Brother", artist: "Art Brut" },
    { placement: 12, songName: "Grandma's Hands", artist: "Bill Withers" },
    { placement: 13, songName: "Ode To My Family", artist: "The Cranberries" },
    { placement: 14, songName: "Neue Zähne Für Meinen Bruder Und Mich", artist: "Superpunk" },
    { placement: 15, songName: "You Are My Sister", artist: "Antony And The Johnsons feat. Boy George" },
    { placement: 16, songName: "Little Sister", artist: "Queens Of The Stone Age" },
    { placement: 17, songName: "Family Portrait", artist: "Pink" },
    { placement: 18, songName: "Geschwisterliebe", artist: "Die Ärzte" },
    { placement: 19, songName: "My Father's Eyes", artist: "Eric Clapton" },
    { placement: 20, songName: "Oft Gefragt", artist: "AnnenMayKantereit" },
    { placement: 21, songName: "My Perfect Cousin", artist: "The Undertones" },
    { placement: 22, songName: "Mother", artist: "IDLES" },
    { placement: 23, songName: "Brothers In Arms", artist: "Dire Straits" },
    { placement: 24, songName: "Hey Jude", artist: "The Beatles" },
    { placement: 25, songName: "Bologna", artist: "Wanda" },
    { placement: 26, songName: "Mama", artist: "Genesis" },
    { placement: 27, songName: "Teach Your Children", artist: "Crosby, Stills, Nash & Young" },
    { placement: 28, songName: "Isn't She Lovely", artist: "Stevie Wonder" },
    { placement: 29, songName: "Oh, Sister", artist: "Bob Dylan" },
    { placement: 30, songName: "He Ain't Heavy, He's My Brother", artist: "The Hollies" },
    { placement: 31, songName: "Sister", artist: "The Black Keys" },
    { placement: 32, songName: "Tears In Heaven", artist: "Eric Clapton" },
    { placement: 33, songName: "Bro Hymn", artist: "Pennywise" },
    { placement: 34, songName: "Papa Don't Preach", artist: "Madonna" },
    { placement: 35, songName: "Family Man", artist: "Fleetwood Mac" },
    { placement: 36, songName: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 37, songName: "Daughter", artist: "Pearl Jam" },
    { placement: 38, songName: "Bridge Over Troubled Water", artist: "Simon & Garfunkel" },
    { placement: 39, songName: "Mother And Child Reunion", artist: "Paul Simon" },
    { placement: 40, songName: "(We Don't Need This) Fascist Groove Thang", artist: "Heaven 17" },
    { placement: 41, songName: "Shakespeare's Sister", artist: "The Smiths" },
    { placement: 42, songName: "Brother Father Mother Sister", artist: "Tim Maia" },
    { placement: 43, songName: "Hey, Ma", artist: "Bon Iver" },
    { placement: 44, songName: "The Mother We Share", artist: "Chvrches" },
    { placement: 45, songName: "Oh, Mama", artist: "The Düsseldorf Düsterboys" },
    { placement: 46, songName: "What's Happening Brother", artist: "Marvin Gaye" },
    { placement: 47, songName: "Mutter", artist: "Rammstein" },
    { placement: 48, songName: "Mother", artist: "Pink Floyd" },
    { placement: 49, songName: "Kooks", artist: "David Bowie" },
    { placement: 50, songName: "Gone Daddy Gone", artist: "Violent Femmes" },
    { placement: 51, songName: "She's Leaving Home", artist: "The Beatles" },
    { placement: 52, songName: "Born To A Family", artist: "The Go-Betweens" },
    { placement: 53, songName: "Ich Will Nicht Werden, Was Mein Alter Ist", artist: "Ton Steine Scherben" },
    { placement: 54, songName: "Song For Our Daughter", artist: "Laura Marling" },
    { placement: 55, songName: "Bloody Mother Fucking Asshole", artist: "Martha Wainwright" },
    { placement: 56, songName: "Sisters Of Mercy", artist: "Leonard Cohen" },
    { placement: 57, songName: "No Son Of Mine", artist: "Genesis" },
    { placement: 58, songName: "Junge", artist: "Die Ärzte" },
    { placement: 59, songName: "Our House", artist: "Madness" },
    { placement: 60, songName: "Mama Said Knock You Out", artist: "LL Cool J" },
    { placement: 61, songName: "I'm My Own Grandpa", artist: "Lonzo & Oscar" },
    { placement: 62, songName: "The Exchange", artist: "Torres" },
    { placement: 63, songName: "Hey Brother", artist: "Avicii" },
    { placement: 64, songName: "Dear Mama", artist: "2Pac" },
    { placement: 65, songName: "The Good Son", artist: "Nick Cave & The Bad Seeds" },
    { placement: 66, songName: "Mommy's Little Monster", artist: "Social Distortion" },
    { placement: 67, songName: "Oh Father", artist: "Madonna" },
    { placement: 68, songName: "Julia", artist: "The Beatles" },
    { placement: 69, songName: "It's Alright Ma (I'm Only Bleeding)", artist: "Bob Dylan" },
    { placement: 70, songName: "Sister Moon", artist: "Sting" },
    { placement: 71, songName: "Puppe", artist: "Rammstein" },
    { placement: 72, songName: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 73, songName: "Mama", artist: "Spice Girls" },
    { placement: 74, songName: "It's A Shame (My Sister)", artist: "Monie Love" },
    { placement: 75, songName: "Daddy", artist: "Coldplay" },
    { placement: 76, songName: "I Can Never Go Home Anymore", artist: "The Shangri-Las" },
    { placement: 77, songName: "Unknown Brother", artist: "The Black Keys" },
    { placement: 78, songName: "Mama", artist: "My Chemical Romance" },
    { placement: 79, songName: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 80, songName: "Papaoutai", artist: "Stromae" },
    { placement: 81, songName: "The Addams Family Theme", artist: "Vic Mizzy & His Orchestra" },
    { placement: 82, songName: "Papa Won't Leave You, Henry", artist: "Nick Cave & The Bad Seeds" },
    { placement: 83, songName: "My Son Calls Another Man Daddy", artist: "Hank Williams" },
    { placement: 84, songName: "Ich Heirate Eine Familie", artist: "Tocotronic" },
    { placement: 85, songName: "Your Mother Should Know", artist: "The Beatles" },
    { placement: 86, songName: "I'll Be There", artist: "The Jackson 5" },
    { placement: 87, songName: "Mother Stands For Comfort", artist: "Kate Bush" },
    { placement: 88, songName: "Vater", artist: "Soap&Skin" },
    { placement: 89, songName: "Meine Schwester", artist: "Tocotronic" },
    { placement: 90, songName: "Dance Little Sister", artist: "Terence Trent D'Arby" },
    { placement: 91, songName: "Brother And Sister", artist: "The Gun Club" },
    { placement: 92, songName: "Death With Dignity", artist: "Sufjan Stevens" },
    { placement: 93, songName: "Lonesome Valley", artist: "Bill Callahan" },
    { placement: 94, songName: "Brother Louie", artist: "Modern Talking" },
    { placement: 95, songName: "Say It Ain't So", artist: "Weezer" },
    { placement: 96, songName: "Nur Zu Besuch", artist: "Die Toten Hosen" },
    { placement: 97, songName: "Randale", artist: "Kraftklub" },
    { placement: 98, songName: "Kids", artist: "MGMT" },
    { placement: 99, songName: "Niemand Wie Ihr", artist: "Feine Sahne Fischfilet" },
    { placement: 100, songName: "Sister Surround", artist: "The Soundtrack Of Our Lives" }]
};

export const drugs: Board = {
  name: 'Flying High - Die 100 besten Drogen-Lieder',
  lines: [
    { placement: 1, songName: "Heroin", artist: "The Velvet Underground" },
    { placement: 2, songName: "White Rabbit", artist: "Jefferson Airplaine" },
    { placement: 3, songName: "The Drugs Don't Work", artist: "The Verve" },
    { placement: 4, songName: "Rehab", artist: "Amy Winehouse" },
    { placement: 5, songName: "I´m Waiting For The Man", artist: "The Velvet Undergound" },
    { placement: 6, songName: "Lucy In The Sky With Diamonds", artist: "The Beatles" },
    { placement: 7, songName: "The Needle And The Damage Done", artist: "Neil Young" },
    { placement: 8, songName: "Feel Good Hit Of The Summer", artist: "Queens Of The Stone Age" },
    { placement: 9, songName: "Purple Haze", artist: "The Jimi Hendrix Experience" },
    { placement: 10, songName: "Under The Bridge", artist: "Red Hot Chili Peppers" },
    { placement: 11, songName: "Golden Brown", artist: "The Stranglers" },
    { placement: 12, songName: "Cocaine", artist: "J. J. Cale" },
    { placement: 13, songName: "Drogen Nehmen Und Rumfahren", artist: "Die Zukunft" },
    { placement: 14, songName: "Am Tag, Als Conny Kramer Starb", artist: "Juliane Werding" },
    { placement: 15, songName: "Needle In The Hay", artist: "Elliott Smith" },
    { placement: 16, songName: "White Lines (Don't Don't Do It)", artist: "Grandmaster Flash & Melle Mel" },
    { placement: 17, songName: "Pusherman", artist: "Curtis Mayfield" },
    { placement: 18, songName: "Cold Turkey", artist: "John Lennon & Plastic Ono Band" },
    { placement: 19, songName: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 20, songName: "Comfortably Numb", artist: "Pink Floyd" },
    { placement: 21, songName: "Eight Miles High", artist: "The Byrds" },
    { placement: 22, songName: "Alkohol", artist: "Herbert Grönemeyer" },
    { placement: 23, songName: "Lithium", artist: "Nirvana" },
    { placement: 24, songName: "True Faith", artist: "New Order" },
    { placement: 25, songName: "You Need The Drugs", artist: "Westbam feat. Richard Butler" },
    { placement: 26, songName: "Gold Dust Woman", artist: "Fleetwood Mac" },
    { placement: 27, songName: "Beetlebum", artist: "Blur" },
    { placement: 28, songName: "Can't Feel My Face", artist: "The Weeknd" },
    { placement: 29, songName: "Because I Got High", artist: "Afroman" },
    { placement: 30, songName: "Hits From The Bong", artist: "Cypress Hill" },
    { placement: 31, songName: "I Wanna Be Sedated", artist: "Ramones" },
    { placement: 32, songName: "Cocaine In My Brain", artist: "Dillinger" },
    { placement: 33, songName: "Where Is My Mind?", artist: "Pixies" },
    { placement: 34, songName: "Higher Than The Sun", artist: "Primal Scream" },
    { placement: 35, songName: "Sister Morphine", artist: "Marianne Faithfull" },
    { placement: 36, songName: "Sorted For E's And Wizz", artist: "Pulp" },
    { placement: 37, songName: "Champagne Supernova", artist: "Oasis" },
    { placement: 38, songName: "Insane In The Brain", artist: "Cypress Hill" },
    { placement: 39, songName: "Perfect Day", artist: "Lou Reed" },
    { placement: 40, songName: "Mother I’ve Taken LSD", artist: "The Flaming Lips" },
    { placement: 41, songName: "Straight Edge", artist: "Minor Threat" },
    { placement: 42, songName: "Sex & Drugs & Rock & Roll", artist: "Ian Dury" },
    { placement: 43, songName: "Hurt", artist: "Nine Inch Nails" },
    { placement: 44, songName: "Mary Jane's Last Dance", artist: "Tom Petty & The Heartbreakers" },
    { placement: 45, songName: "My Friend Jack", artist: "The Smoke" },
    { placement: 46, songName: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 47, songName: "Ebeneezer Goode", artist: "The Shamen" },
    { placement: 48, songName: "Never Let Me Down Again", artist: "Depeche Mode" },
    { placement: 49, songName: "Ganz Wien", artist: "Falco" },
    { placement: 50, songName: "3 Tage Wach", artist: "Lützenkirchen" },
    { placement: 51, songName: "Master Of Puppets", artist: "Metallica" },
    { placement: 52, songName: "Bianco", artist: "Yung Hurn & RIN" },
    { placement: 53, songName: "Cigarettes & Alcohol", artist: "Oasis" },
    { placement: 54, songName: "Just One Fix", artist: "Ministry" },
    { placement: 55, songName: "The Pusher", artist: "Steppenwolf" },
    { placement: 56, songName: "Drugs", artist: "Upsahl" },
    { placement: 57, songName: "Mutter, Der Mann Mit Dem Koks Ist Da", artist: "Falco" },
    { placement: 58, songName: "Special K", artist: "Placebo" },
    { placement: 59, songName: "Swimming Pools (Drank)", artist: "Kendrick Lamar" },
    { placement: 60, songName: "Heute Schütte Ich Mich Zu", artist: "Karl Dall" },
    { placement: 61, songName: "Eight Miles High", artist: "Hüsker Dü" },
    { placement: 62, songName: "High By The Beach", artist: "Lana Del Rey" },
    { placement: 63, songName: "My Drug Buddy", artist: "The Lemonheads" },
    { placement: 64, songName: "Brown Sugar", artist: "The Rolling Stones" },
    { placement: 65, songName: "Hurt", artist: "Johnny Cash" },
    { placement: 66, songName: "White Punks On Dope", artist: "The Tubes" },
    { placement: 67, songName: "Cola-Wodka", artist: "Holger Biege" },
    { placement: 68, songName: "Alabama Song (Whisky Bar)", artist: "The Doors" },
    { placement: 69, songName: "Why’d You Only Call Me When You’re High?", artist: "Arctic Monkeys" },
    { placement: 70, songName: "I'm Your Pusher", artist: "Ice-T" },
    { placement: 71, songName: "Hash Pipe", artist: "Weezer" },
    { placement: 72, songName: "Brown Sugar", artist: "D'Angelo" },
    { placement: 73, songName: "Tag Am Meer", artist: "Die Fantastischen Vier" },
    { placement: 74, songName: "Sugar Man", artist: "Rodriguez" },
    { placement: 75, songName: "Mix Mir Einen Drink", artist: "Feeling B" },
    { placement: 76, songName: "Mary Jane", artist: "Rick James" },
    { placement: 77, songName: "Bongzimmer", artist: "SXTN" },
    { placement: 78, songName: "Crystal Meth In Brandenburg", artist: "Grim104" },
    { placement: 79, songName: "Hotel California", artist: "Eagles" },
    { placement: 80, songName: "Cocaine", artist: "Eric Clapton" },
    { placement: 81, songName: "Willst Du", artist: "Alligatoah" },
    { placement: 82, songName: "Needle Of Death", artist: "Bert Jansch" },
    { placement: 83, songName: "Kokain", artist: "Hannes Wader" },
    { placement: 84, songName: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, songName: "Rainy Day Women #12 & 35", artist: "Bob Dylan" },
    { placement: 86, songName: "Karlsquell", artist: "Slime" },
    { placement: 87, songName: "Xanny", artist: "Billie Eilish" },
    { placement: 88, songName: "Ashes To Ashes", artist: "David Bowie" },
    { placement: 89, songName: "White Horse", artist: "Laid Back" },
    { placement: 90, songName: "We Are All On Drugs", artist: "Weezer" },
    { placement: 91, songName: "Not If You Were The Last Junkie On Earth", artist: "The Dandy Warhols" },
    { placement: 92, songName: "Pass That Dutch", artist: "Missy Elliott" },
    { placement: 93, songName: "Lost", artist: "Frank Ocean" },
    { placement: 94, songName: "Blinded By The Lights", artist: "The Streets" },
    { placement: 95, songName: "Sam Stone", artist: "John Prine" },
    { placement: 96, songName: "Nicotine", artist: "Chef'Special" },
    { placement: 97, songName: "Novacane", artist: "Frank Ocean" },
    { placement: 98, songName: "Strychnine", artist: "The Sonics" },
    { placement: 99, songName: "King Heroin", artist: "James Brown" },
    { placement: 100, songName: "Zeit Steht", artist: "Trettmann feat. Alli Neumann" },
  ]
};
