export interface BoardLineItem {
  artist: string;
  title: string;
  placement: number;
  boardPosition?: string;
}

export interface Board {
  name: string;
  lines: Array<BoardLineItem>
}

export const animals: Board = {
  name: 'Animals - Die 100 besten Lieder mit Tieren',
  lines: [
    { placement: 1, title: "I Wanna Be Your Dog", artist: "Iggy & The Stooges" },
    { placement: 2, title: "The Lovecats", artist: "The Cure" },
    { placement: 3, title: "Blackbird", artist: "The Beatles" },
    { placement: 4, title: "When Doves Cry", artist: "Prince & The Revolution" },
    { placement: 5, title: "Rock Lobster", artist: "The B-52's" },
    { placement: 6, title: "Wild Horses", artist: "The Rollling Stones" },
    { placement: 7, title: "Black Dog", artist: "Led Zeppelin" },
    { placement: 8, title: "A Horse With No Name", artist: "America" },
    { placement: 9, title: "I Am The Walrus", artist: "The Beatles" },
    { placement: 10, title: "Monkey Gone To Heaven", artist: "Pixies" },
    { placement: 11, title: "Dog Days Are Over", artist: "Florence + The Machine" },
    { placement: 12, title: "Nellie The Elephant", artist: "Toy Dolls" },
    { placement: 13, title: "Statdtaffe", artist: "Peter Fox" },
    { placement: 14, title: "Eisbär", artist: "Grauzone" },
    { placement: 15, title: "Elephant", artist: "Tame Impala" },
    { placement: 16, title: "Buffalo Stance", artist: "Neneh Cherry" },
    { placement: 17, title: "Eye Of The Tiger", artist: "Survivor" },
    { placement: 18, title: "Hounds Of Love", artist: "Kate Bush" },
    { placement: 19, title: "Barracuda", artist: "Heart" },
    { placement: 20, title: "Claudia Hat 'Nen Schäferhund", artist: "Die Ärzte" },
    { placement: 21, title: "Hungry Like The Wolf", artist: "Duran Duran" },
    { placement: 22, title: "Human Fly", artist: "The Cramps" },
    { placement: 23, title: "Cat People (Putting Out Fire)", artist: "David Bowie" },
    { placement: 24, title: "Bird On The Wire", artist: "Leonard Cohen" },
    { placement: 25, title: "Can Your Pussy Do The Dog?", artist: "The Cramps" },
    { placement: 26, title: "I Like Birds", artist: "Eels" },
    { placement: 27, title: "Albatros", artist: "Karat" },
    { placement: 28, title: "Meat Is Murder", artist: "The Smiths" },
    { placement: 29, title: "Die Tse Tse Fliege", artist: "Oma Hans" },
    { placement: 30, title: "White Rabbit", artist: "Jefferson Airplane" },
    { placement: 31, title: "The Lion Sleeps Tonight", artist: "The Tokens" },
    { placement: 32, title: "Walkin’ My Cat Named Dog", artist: "Norma Tanega" },
    { placement: 33, title: "Who Let The Dogs Out?", artist: "Baha Men" },
    { placement: 34, title: "I’m Like A Bird", artist: "Nelly Furtado" },
    { placement: 35, title: "Boris The Spider", artist: "The Who" },
    { placement: 36, title: "Surfin' Bird", artist: "The Trashmen" },
    { placement: 37, title: "Fly Like An Eagle", artist: "Steve Miller Band" },
    { placement: 38, title: "Hound Dog", artist: "Elvis Presley" },
    { placement: 39, title: "Katzeklo", artist: "Helge Schneider" },
    { placement: 40, title: "Die Tiere Sind Unruhig", artist: "Kante" },
    { placement: 41, title: "Stray Cat Strut", artist: "Stray Cats" },
    { placement: 42, title: "Wolf Like Me", artist: "TV On The Radio" },
    { placement: 43, title: "Crocodile Rock", artist: "Elton John" },
    { placement: 44, title: "Cats And Dogs", artist: "Gorilla Biscuits" },
    { placement: 45, title: "Endlich Einmal", artist: "Tomte" },
    { placement: 46, title: "Shock The Monkey", artist: "Peter Gabriel" },
    { placement: 47, title: "Zum Laichen Und Sterben Ziehen Die Lachse Den Fluss Hinauf", artist: "Thees Uhlmann" },
    { placement: 48, title: "Animal", artist: "Pearl Jam" },
    { placement: 49, title: "Schwan", artist: "Turbostaat" },
    { placement: 50, title: "White Bird", artist: "It`s A Beautiful Day" },
    { placement: 51, title: "Karl Der Käfer", artist: "Gänsehaut" },
    { placement: 52, title: "Little Lion Man", artist: "Mumford & Sons" },
    { placement: 53, title: "Fox On The Run", artist: "The Sweet" },
    { placement: 54, title: "Animal", artist: "Miike Snow" },
    { placement: 55, title: "Ride A White Swan", artist: "T. Rex" },
    { placement: 56, title: "Hund", artist: "Yukno" },
    { placement: 57, title: "Bird Song", artist: "Lene Lovich" },
    { placement: 58, title: "Horse And I", artist: "Bat For Lashes" },
    { placement: 59, title: "I Cut Like A Buffalo", artist: "The Dead Weather" },
    { placement: 60, title: "Brass Monkey", artist: "Beastie Boys" },
    { placement: 61, title: "Three Little Birds", artist: "Bob Marley & The Wailers" },
    { placement: 62, title: "Coyote", artist: "Joni Mitchell" },
    { placement: 63, title: "Hound Dog", artist: "Big Mama Thornton" },
    { placement: 64, title: "The Lamb Lies Down On Broadway", artist: "Genesis" },
    { placement: 65, title: "Piggies", artist: "The Beatles" },
    { placement: 66, title: "Buffalo Soldier", artist: "Bob Marley & The Wailers\n" },
    { placement: 67, title: "Land: Horses / Land Of A Thousand Dances / La Mer(de)", artist: "Patti Smith" },
    { placement: 68, title: "Eagle", artist: "ABBA" },
    { placement: 69, title: "Teach Me Tiger", artist: "April Stevens" },
    { placement: 70, title: "Atomic Dog", artist: "George Clinton" },
    { placement: 71, title: "Birds", artist: "Frida Hyvönen" },
    { placement: 72, title: "I Love My Dog", artist: "Cat Stevens" },
    { placement: 73, title: "Karma Chameleon", artist: "Culture Club" },
    { placement: 74, title: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 75, title: "Octopus‘s Garden", artist: "The Beatles" },
    { placement: 76, title: "Sheep", artist: "The Housemartins" },
    { placement: 77, title: "Do The Dog", artist: "The Specials" },
    { placement: 78, title: "The Fox In The Snow", artist: "Belle And Sebastian" },
    { placement: 79, title: "Albatross", artist: "Fleetwood Mac" },
    { placement: 80, title: "Crickets Sing For Anamaria", artist: "Marcos Valle" },
    { placement: 81, title: "N' Käfer Auf'm Blatt", artist: "Chicorée" },
    { placement: 82, title: "Mister, Would You Please Help My Pony?", artist: "Ween" },
    { placement: 83, title: "Ich Und Mein Freund Die Katze", artist: "Interzone" },
    { placement: 84, title: "Iron Lion Zion", artist: "Bob Marley" },
    { placement: 85, title: "(Let Me Be Your) Teddy Bear", artist: "Elvis Presley" },
    { placement: 86, title: "Pink Panther Theme", artist: "Henry Mancini" },
    { placement: 87, title: "Sparrow", artist: "Marvin Gaye" },
    { placement: 88, title: "The Snake", artist: "Al Wilson" },
    { placement: 89, title: "Der Letzte Kranich", artist: "Tocotronic" },
    { placement: 90, title: "Free Bird", artist: "Lynyrd Skynyrd" },
    { placement: 91, title: "Rhinoceros", artist: "The Smashing Pumpkins" },
    { placement: 92, title: "Me And My Monkey", artist: "Robbie Williams" },
    { placement: 93, title: "We Are The Pigs", artist: "Suede" },
    { placement: 94, title: "Too Many Puppies", artist: "Primus" },
    { placement: 95, title: "Sheep", artist: "Pink Floyd" },
    { placement: 96, title: "Long Snake Moan", artist: "PJ Harvey" },
    { placement: 97, title: "Lullaby", artist: "The Cure" },
    { placement: 98, title: "Pet Sematary", artist: "Ramones" },
    { placement: 99, title: "Delilah", artist: "Queen" },
    { placement: 100, title: "Anaconda", artist: "Nicki Minaj" }]
};

export const numbers: Board = {
  name: 'Magic Numbers - Die 100 besten Songs mit Zahlen im Titel',
  lines: [
    { placement: 1, title: "Song 2", artist: "Blur" },
    { placement: 2, title: "1234", artist: "Feist" },
    { placement: 3, title: "1999", artist: "Prince" },
    { placement: 4, title: "Seven Nation Army", artist: "The White Stripes" },
    { placement: 5, title: "50 Ways To Leave Your Lover", artist: "Paul Simon" },
    { placement: 6, title: "One", artist: "U2" },
    { placement: 7, title: "Disco 2000", artist: "Pulp" },
    { placement: 8, title: "1979", artist: "The Smashing Pumpkins" },
    { placement: 9, title: "99 Problems", artist: "Jay-Z" },
    { placement: 10, title: "One", artist: "Metallica" },
    { placement: 11, title: "99 Luftballons", artist: "Nena" },
    { placement: 12, title: "Edge Of Seventeen", artist: "Stevie Nicks" },
    { placement: 13, title: "48 Crash", artist: "Suzi Quatro" },
    { placement: 14, title: "54-46 Was My Number", artist: "Toots & The Maytals" },
    { placement: 15, title: "1969", artist: "The Stooges" },
    { placement: 16, title: "2000 Light Years From Home", artist: "The Rolling Stones" },
    { placement: 17, title: "10.15 Saturday Night", artist: "The Cure" },
    { placement: 18, title: "96 Tears", artist: "? & The Mysterians" },
    { placement: 19, title: "Eight Days A Week", artist: "The Beatles" },
    { placement: 20, title: "20th Century Boy", artist: "T. Rex" },
    { placement: 21, title: "100%", artist: "Sonic Youth" },
    { placement: 22, title: "Thirteen", artist: "Big Star" },
    { placement: 23, title: "2-4-6-8 Motorway", artist: "Tom Robinson Band" },
    { placement: 24, title: "6060-842", artist: "The B-52's" },
    { placement: 25, title: "Nummern", artist: "Kraftwerk" },
    { placement: 26, title: "Five Years", artist: "David Bowie" },
    { placement: 27, title: "Nothing Compares 2 U", artist: "Sinéad O' Connor" },
    { placement: 28, title: "Eight Miles High\n", artist: "The Byrds\n" },
    { placement: 29, title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
    { placement: 30, title: "12:15", artist: "The Strokes" },
    { placement: 31, title: "The Magic Number", artist: "De La Soul" },
    { placement: 32, title: "If 6 Was 9", artist: "The Jimi Hendrix Experience" },
    { placement: 33, title: "7 Seconds", artist: "Youssou N`Dour & Neneh Cherry" },
    { placement: 34, title: "12XU", artist: "Wire" },
    { placement: 35, title: "When I'm Sixty-Four", artist: "The Beatles" },
    { placement: 36, title: "One", artist: "Aimee Mann" },
    { placement: 37, title: "The Four Horsemen", artist: "Aphrodite`s Child" },
    { placement: 38, title: "The Number Of The Beast", artist: "Iron Maiden" },
    { placement: 39, title: "2000 Mädchen", artist: "Die Ärzte" },
    { placement: 40, title: "Three Is A Magic Number", artist: "Bob Dorough" },
    { placement: 41, title: "48 Stunden", artist: "Kettcar" },
    { placement: 42, title: "19", artist: "Paul Hardcastle" },
    { placement: 43, title: "Four Women", artist: "Nina Simone" },
    { placement: 44, title: "1901", artist: "Phoenix" },
    { placement: 45, title: "Little 15", artist: "Depeche Mode" },
    { placement: 46, title: "Little Numbers", artist: "Boy" },
    { placement: 47, title: "9 To 5", artist: "Dolly Parton" },
    { placement: 48, title: "911 Is A Joke", artist: "Public Enemy" },
    { placement: 49, title: "Waltz #2 (XO)", artist: "Elliott Smith" },
    { placement: 50, title: "Thirteen", artist: "Jingo De Lunch" },
    { placement: 51, title: "Highway 61 Revisited", artist: "Bob Dylan" },
    { placement: 52, title: "50ft Queenie", artist: "PJ Harvey" },
    { placement: 53, title: "One", artist: "Harry Nilsson" },
    { placement: 54, title: "Tausend Tränen Tief", artist: "Blumfeld" },
    { placement: 55, title: "21st Century (Digital Boy)", artist: "Bad Religion" },
    { placement: 56, title: "Seventeen", artist: "Sharon Van Etten" },
    { placement: 57, title: "2 Oder 3 Dinge, Die Ich Von Dir Weiß", artist: "Blumfeld" },
    { placement: 58, title: "Zehn", artist: "Farin Urlaub Racing Team" },
    { placement: 59, title: "Eins Und Eins, Das Macht Zwei", artist: "Hildegard Knef" },
    { placement: 60, title: "Paris 1919", artist: "John Cale" },
    { placement: 61, title: "51st State", artist: "New Model Army" },
    { placement: 62, title: "Two Weeks", artist: "FKA Twigs" },
    { placement: 63, title: "Five To One", artist: "The Doors" },
    { placement: 64, title: "52 Girls", artist: "The B-52's" },
    { placement: 65, title: "Nr. 48", artist: "Engerling" },
    { placement: 66, title: "One More Time", artist: "Daft Punk" },
    { placement: 67, title: "25 Or 6 To 4", artist: "Chicago" },
    { placement: 68, title: "54/40 Or Fight", artist: "Dead Moon" },
    { placement: 69, title: "The Magnificent Seven", artist: "The Clash" },
    { placement: 70, title: "Chelsea Hotel #2", artist: "Leonard Cohen" },
    { placement: 71, title: "Take Five", artist: "Dave Brubeck Quartet" },
    { placement: 72, title: "Revolution 9", artist: "The Beatles" },
    { placement: 73, title: "One", artist: "Three Dog Night" },
    { placement: 74, title: "Forty Six & 2", artist: "Tool" },
    { placement: 75, title: "1/2 Lovesong", artist: "Die Ärzte" },
    { placement: 76, title: "Seventeen Seconds", artist: "The Cure" },
    { placement: 77, title: "Thirteen\n", artist: "Johnny Cash" },
    { placement: 78, title: "1,2,3,4", artist: "Wanda" },
    { placement: 79, title: "2 Become 1", artist: "Spice Girls" },
    { placement: 80, title: "3 Millionen", artist: "Bosse" },
    { placement: 81, title: "33 \"GOD\"", artist: "Bon Iver" },
    { placement: 82, title: "1000 Und 1 Nacht (Zoom!)", artist: "Klaus Lage Band" },
    { placement: 83, title: "Summer Of `69", artist: "Bryan Adams" },
    { placement: 84, title: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, title: "Route 66", artist: "Chuck Berry" },
    { placement: 86, title: "9010", artist: "Kummer" },
    { placement: 87, title: "23", artist: "Jimmy Eat World" },
    { placement: 88, title: "I-94", artist: "Radio Birdman" },
    { placement: 89, title: "Chant No. 1 (I Don't Need This Pressure On)", artist: "Spandau Ballet" },
    { placement: 90, title: "Mit 66 Jahren", artist: "Udo Jürgens" },
    { placement: 91, title: "Perfect 10", artist: "The Beautiful South" },
    { placement: 92, title: "Nineteen Hunderd And Eighty Five", artist: "Paul McCartney & Wings" },
    { placement: 93, title: "3 MC's And 1 DJ", artist: "Beastie Boys" },
    { placement: 94, title: "Links 2-3-4", artist: "Rammstein" },
    { placement: 95, title: "One", artist: "Johnny Cash" },
    { placement: 96, title: "Care Of Cell 44", artist: "The Zombies" },
    { placement: 97, title: "1-2 5", artist: "The Haunted" },
    { placement: 98, title: "19th Nervous Breakdown", artist: "The Rolling Stones" },
    { placement: 99, title: "'39", artist: "Queen" },
    { placement: 100, title: "4 Degrees", artist: "Anohni" }]
};

export const family: Board = {
  name: 'We Are Family - Die 100 besten Familienlieder',
  lines: [
    { placement: 1, title: "Family Affair", artist: "Sly & The Family Stone" },
    { placement: 2, title: "Father And Son", artist: "Cat Stevens" },
    { placement: 3, title: "We Are Family", artist: "Sister Sledge" },
    { placement: 4, title: "Mother", artist: "Danzig" },
    { placement: 5, title: "We're A Happy Family", artist: "Ramones" },
    { placement: 6, title: "Mother", artist: "John Lennon & Plastic Ono Band" },
    { placement: 7, title: "Sisters Are Doin' It For Themselves", artist: "Eurythmics & Aretha Franklin" },
    { placement: 8, title: "Papa Was A Rollin' Stone", artist: "The Temptations" },
    { placement: 9, title: "Family Affair", artist: "Mary J. Blige" },
    { placement: 10, title: "Father Figure", artist: "George Michael" },
    { placement: 11, title: "My Little Brother", artist: "Art Brut" },
    { placement: 12, title: "Grandma's Hands", artist: "Bill Withers" },
    { placement: 13, title: "Ode To My Family", artist: "The Cranberries" },
    { placement: 14, title: "Neue Zähne Für Meinen Bruder Und Mich", artist: "Superpunk" },
    { placement: 15, title: "You Are My Sister", artist: "Antony And The Johnsons feat. Boy George" },
    { placement: 16, title: "Little Sister", artist: "Queens Of The Stone Age" },
    { placement: 17, title: "Family Portrait", artist: "Pink" },
    { placement: 18, title: "Geschwisterliebe", artist: "Die Ärzte" },
    { placement: 19, title: "My Father's Eyes", artist: "Eric Clapton" },
    { placement: 20, title: "Oft Gefragt", artist: "AnnenMayKantereit" },
    { placement: 21, title: "My Perfect Cousin", artist: "The Undertones" },
    { placement: 22, title: "Mother", artist: "IDLES" },
    { placement: 23, title: "Brothers In Arms", artist: "Dire Straits" },
    { placement: 24, title: "Hey Jude", artist: "The Beatles" },
    { placement: 25, title: "Bologna", artist: "Wanda" },
    { placement: 26, title: "Mama", artist: "Genesis" },
    { placement: 27, title: "Teach Your Children", artist: "Crosby, Stills, Nash & Young" },
    { placement: 28, title: "Isn't She Lovely", artist: "Stevie Wonder" },
    { placement: 29, title: "Oh, Sister", artist: "Bob Dylan" },
    { placement: 30, title: "He Ain't Heavy, He's My Brother", artist: "The Hollies" },
    { placement: 31, title: "Sister", artist: "The Black Keys" },
    { placement: 32, title: "Tears In Heaven", artist: "Eric Clapton" },
    { placement: 33, title: "Bro Hymn", artist: "Pennywise" },
    { placement: 34, title: "Papa Don't Preach", artist: "Madonna" },
    { placement: 35, title: "Family Man", artist: "Fleetwood Mac" },
    { placement: 36, title: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 37, title: "Daughter", artist: "Pearl Jam" },
    { placement: 38, title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel" },
    { placement: 39, title: "Mother And Child Reunion", artist: "Paul Simon" },
    { placement: 40, title: "(We Don't Need This) Fascist Groove Thang", artist: "Heaven 17" },
    { placement: 41, title: "Shakespeare's Sister", artist: "The Smiths" },
    { placement: 42, title: "Brother Father Mother Sister", artist: "Tim Maia" },
    { placement: 43, title: "Hey, Ma", artist: "Bon Iver" },
    { placement: 44, title: "The Mother We Share", artist: "Chvrches" },
    { placement: 45, title: "Oh, Mama", artist: "The Düsseldorf Düsterboys" },
    { placement: 46, title: "What's Happening Brother", artist: "Marvin Gaye" },
    { placement: 47, title: "Mutter", artist: "Rammstein" },
    { placement: 48, title: "Mother", artist: "Pink Floyd" },
    { placement: 49, title: "Kooks", artist: "David Bowie" },
    { placement: 50, title: "Gone Daddy Gone", artist: "Violent Femmes" },
    { placement: 51, title: "She's Leaving Home", artist: "The Beatles" },
    { placement: 52, title: "Born To A Family", artist: "The Go-Betweens" },
    { placement: 53, title: "Ich Will Nicht Werden, Was Mein Alter Ist", artist: "Ton Steine Scherben" },
    { placement: 54, title: "Song For Our Daughter", artist: "Laura Marling" },
    { placement: 55, title: "Bloody Mother Fucking Asshole", artist: "Martha Wainwright" },
    { placement: 56, title: "Sisters Of Mercy", artist: "Leonard Cohen" },
    { placement: 57, title: "No Son Of Mine", artist: "Genesis" },
    { placement: 58, title: "Junge", artist: "Die Ärzte" },
    { placement: 59, title: "Our House", artist: "Madness" },
    { placement: 60, title: "Mama Said Knock You Out", artist: "LL Cool J" },
    { placement: 61, title: "I'm My Own Grandpa", artist: "Lonzo & Oscar" },
    { placement: 62, title: "The Exchange", artist: "Torres" },
    { placement: 63, title: "Hey Brother", artist: "Avicii" },
    { placement: 64, title: "Dear Mama", artist: "2Pac" },
    { placement: 65, title: "The Good Son", artist: "Nick Cave & The Bad Seeds" },
    { placement: 66, title: "Mommy's Little Monster", artist: "Social Distortion" },
    { placement: 67, title: "Oh Father", artist: "Madonna" },
    { placement: 68, title: "Julia", artist: "The Beatles" },
    { placement: 69, title: "It's Alright Ma (I'm Only Bleeding)", artist: "Bob Dylan" },
    { placement: 70, title: "Sister Moon", artist: "Sting" },
    { placement: 71, title: "Puppe", artist: "Rammstein" },
    { placement: 72, title: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 73, title: "Mama", artist: "Spice Girls" },
    { placement: 74, title: "It's A Shame (My Sister)", artist: "Monie Love" },
    { placement: 75, title: "Daddy", artist: "Coldplay" },
    { placement: 76, title: "I Can Never Go Home Anymore", artist: "The Shangri-Las" },
    { placement: 77, title: "Unknown Brother", artist: "The Black Keys" },
    { placement: 78, title: "Mama", artist: "My Chemical Romance" },
    { placement: 79, title: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 80, title: "Papaoutai", artist: "Stromae" },
    { placement: 81, title: "The Addams Family Theme", artist: "Vic Mizzy & His Orchestra" },
    { placement: 82, title: "Papa Won't Leave You, Henry", artist: "Nick Cave & The Bad Seeds" },
    { placement: 83, title: "My Son Calls Another Man Daddy", artist: "Hank Williams" },
    { placement: 84, title: "Ich Heirate Eine Familie", artist: "Tocotronic" },
    { placement: 85, title: "Your Mother Should Know", artist: "The Beatles" },
    { placement: 86, title: "I'll Be There", artist: "The Jackson 5" },
    { placement: 87, title: "Mother Stands For Comfort", artist: "Kate Bush" },
    { placement: 88, title: "Vater", artist: "Soap&Skin" },
    { placement: 89, title: "Meine Schwester", artist: "Tocotronic" },
    { placement: 90, title: "Dance Little Sister", artist: "Terence Trent D'Arby" },
    { placement: 91, title: "Brother And Sister", artist: "The Gun Club" },
    { placement: 92, title: "Death With Dignity", artist: "Sufjan Stevens" },
    { placement: 93, title: "Lonesome Valley", artist: "Bill Callahan" },
    { placement: 94, title: "Brother Louie", artist: "Modern Talking" },
    { placement: 95, title: "Say It Ain't So", artist: "Weezer" },
    { placement: 96, title: "Nur Zu Besuch", artist: "Die Toten Hosen" },
    { placement: 97, title: "Randale", artist: "Kraftklub" },
    { placement: 98, title: "Kids", artist: "MGMT" },
    { placement: 99, title: "Niemand Wie Ihr", artist: "Feine Sahne Fischfilet" },
    { placement: 100, title: "Sister Surround", artist: "The Soundtrack Of Our Lives" }]
};

export const drugs: Board = {
  name: 'Flying High - Die 100 besten Drogen-Lieder',
  lines: [
    { placement: 1, title: "Heroin", artist: "The Velvet Underground" },
    { placement: 2, title: "White Rabbit", artist: "Jefferson Airplaine" },
    { placement: 3, title: "The Drugs Don't Work", artist: "The Verve" },
    { placement: 4, title: "Rehab", artist: "Amy Winehouse" },
    { placement: 5, title: "I´m Waiting For The Man", artist: "The Velvet Undergound" },
    { placement: 6, title: "Lucy In The Sky With Diamonds", artist: "The Beatles" },
    { placement: 7, title: "The Needle And The Damage Done", artist: "Neil Young" },
    { placement: 8, title: "Feel Good Hit Of The Summer", artist: "Queens Of The Stone Age" },
    { placement: 9, title: "Purple Haze", artist: "The Jimi Hendrix Experience" },
    { placement: 10, title: "Under The Bridge", artist: "Red Hot Chili Peppers" },
    { placement: 11, title: "Golden Brown", artist: "The Stranglers" },
    { placement: 12, title: "Cocaine", artist: "J. J. Cale" },
    { placement: 13, title: "Drogen Nehmen Und Rumfahren", artist: "Die Zukunft" },
    { placement: 14, title: "Am Tag, Als Conny Kramer Starb", artist: "Juliane Werding" },
    { placement: 15, title: "Needle In The Hay", artist: "Elliott Smith" },
    { placement: 16, title: "White Lines (Don't Don't Do It)", artist: "Grandmaster Flash & Melle Mel" },
    { placement: 17, title: "Pusherman", artist: "Curtis Mayfield" },
    { placement: 18, title: "Cold Turkey", artist: "John Lennon & Plastic Ono Band" },
    { placement: 19, title: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 20, title: "Comfortably Numb", artist: "Pink Floyd" },
    { placement: 21, title: "Eight Miles High", artist: "The Byrds" },
    { placement: 22, title: "Alkohol", artist: "Herbert Grönemeyer" },
    { placement: 23, title: "Lithium", artist: "Nirvana" },
    { placement: 24, title: "True Faith", artist: "New Order" },
    { placement: 25, title: "You Need The Drugs", artist: "Westbam feat. Richard Butler" },
    { placement: 26, title: "Gold Dust Woman", artist: "Fleetwood Mac" },
    { placement: 27, title: "Beetlebum", artist: "Blur" },
    { placement: 28, title: "Can't Feel My Face", artist: "The Weeknd" },
    { placement: 29, title: "Because I Got High", artist: "Afroman" },
    { placement: 30, title: "Hits From The Bong", artist: "Cypress Hill" },
    { placement: 31, title: "I Wanna Be Sedated", artist: "Ramones" },
    { placement: 32, title: "Cocaine In My Brain", artist: "Dillinger" },
    { placement: 33, title: "Where Is My Mind?", artist: "Pixies" },
    { placement: 34, title: "Higher Than The Sun", artist: "Primal Scream" },
    { placement: 35, title: "Sister Morphine", artist: "Marianne Faithfull" },
    { placement: 36, title: "Sorted For E's And Wizz", artist: "Pulp" },
    { placement: 37, title: "Champagne Supernova", artist: "Oasis" },
    { placement: 38, title: "Insane In The Brain", artist: "Cypress Hill" },
    { placement: 39, title: "Perfect Day", artist: "Lou Reed" },
    { placement: 40, title: "Mother I’ve Taken LSD", artist: "The Flaming Lips" },
    { placement: 41, title: "Straight Edge", artist: "Minor Threat" },
    { placement: 42, title: "Sex & Drugs & Rock & Roll", artist: "Ian Dury" },
    { placement: 43, title: "Hurt", artist: "Nine Inch Nails" },
    { placement: 44, title: "Mary Jane's Last Dance", artist: "Tom Petty & The Heartbreakers" },
    { placement: 45, title: "My Friend Jack", artist: "The Smoke" },
    { placement: 46, title: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 47, title: "Ebeneezer Goode", artist: "The Shamen" },
    { placement: 48, title: "Never Let Me Down Again", artist: "Depeche Mode" },
    { placement: 49, title: "Ganz Wien", artist: "Falco" },
    { placement: 50, title: "3 Tage Wach", artist: "Lützenkirchen" },
    { placement: 51, title: "Master Of Puppets", artist: "Metallica" },
    { placement: 52, title: "Bianco", artist: "Yung Hurn & RIN" },
    { placement: 53, title: "Cigarettes & Alcohol", artist: "Oasis" },
    { placement: 54, title: "Just One Fix", artist: "Ministry" },
    { placement: 55, title: "The Pusher", artist: "Steppenwolf" },
    { placement: 56, title: "Drugs", artist: "Upsahl" },
    { placement: 57, title: "Mutter, Der Mann Mit Dem Koks Ist Da", artist: "Falco" },
    { placement: 58, title: "Special K", artist: "Placebo" },
    { placement: 59, title: "Swimming Pools (Drank)", artist: "Kendrick Lamar" },
    { placement: 60, title: "Heute Schütte Ich Mich Zu", artist: "Karl Dall" },
    { placement: 61, title: "Eight Miles High", artist: "Hüsker Dü" },
    { placement: 62, title: "High By The Beach", artist: "Lana Del Rey" },
    { placement: 63, title: "My Drug Buddy", artist: "The Lemonheads" },
    { placement: 64, title: "Brown Sugar", artist: "The Rolling Stones" },
    { placement: 65, title: "Hurt", artist: "Johnny Cash" },
    { placement: 66, title: "White Punks On Dope", artist: "The Tubes" },
    { placement: 67, title: "Cola-Wodka", artist: "Holger Biege" },
    { placement: 68, title: "Alabama Song (Whisky Bar)", artist: "The Doors" },
    { placement: 69, title: "Why’d You Only Call Me When You’re High?", artist: "Arctic Monkeys" },
    { placement: 70, title: "I'm Your Pusher", artist: "Ice-T" },
    { placement: 71, title: "Hash Pipe", artist: "Weezer" },
    { placement: 72, title: "Brown Sugar", artist: "D'Angelo" },
    { placement: 73, title: "Tag Am Meer", artist: "Die Fantastischen Vier" },
    { placement: 74, title: "Sugar Man", artist: "Rodriguez" },
    { placement: 75, title: "Mix Mir Einen Drink", artist: "Feeling B" },
    { placement: 76, title: "Mary Jane", artist: "Rick James" },
    { placement: 77, title: "Bongzimmer", artist: "SXTN" },
    { placement: 78, title: "Crystal Meth In Brandenburg", artist: "Grim104" },
    { placement: 79, title: "Hotel California", artist: "Eagles" },
    { placement: 80, title: "Cocaine", artist: "Eric Clapton" },
    { placement: 81, title: "Willst Du", artist: "Alligatoah" },
    { placement: 82, title: "Needle Of Death", artist: "Bert Jansch" },
    { placement: 83, title: "Kokain", artist: "Hannes Wader" },
    { placement: 84, title: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, title: "Rainy Day Women #12 & 35", artist: "Bob Dylan" },
    { placement: 86, title: "Karlsquell", artist: "Slime" },
    { placement: 87, title: "Xanny", artist: "Billie Eilish" },
    { placement: 88, title: "Ashes To Ashes", artist: "David Bowie" },
    { placement: 89, title: "White Horse", artist: "Laid Back" },
    { placement: 90, title: "We Are All On Drugs", artist: "Weezer" },
    { placement: 91, title: "Not If You Were The Last Junkie On Earth", artist: "The Dandy Warhols" },
    { placement: 92, title: "Pass That Dutch", artist: "Missy Elliott" },
    { placement: 93, title: "Lost", artist: "Frank Ocean" },
    { placement: 94, title: "Blinded By The Lights", artist: "The Streets" },
    { placement: 95, title: "Sam Stone", artist: "John Prine" },
    { placement: 96, title: "Nicotine", artist: "Chef'Special" },
    { placement: 97, title: "Novacane", artist: "Frank Ocean" },
    { placement: 98, title: "Strychnine", artist: "The Sonics" },
    { placement: 99, title: "King Heroin", artist: "James Brown" },
    { placement: 100, title: "Zeit Steht", artist: "Trettmann feat. Alli Neumann" },
  ]
};
