export interface BoardLineItem {
  artist: string;
  song: string;
  placement: number;
}

export interface Board {
  name: string;
  lines: Array<BoardLineItem>
}

export const animals: Board = {
  name: 'Animals - Die 100 besten Lieder mit Tieren',
  lines: [
    { placement: 1, song: "I Wanna Be Your Dog", artist: "Iggy & The Stooges" },
    { placement: 2, song: "The Lovecats", artist: "The Cure" },
    { placement: 3, song: "Blackbird", artist: "The Beatles" },
    { placement: 4, song: "When Doves Cry", artist: "Prince & The Revolution" },
    { placement: 5, song: "Rock Lobster", artist: "The B-52's" },
    { placement: 6, song: "Wild Horses", artist: "The Rollling Stones" },
    { placement: 7, song: "Black Dog", artist: "Led Zeppelin" },
    { placement: 8, song: "A Horse With No Name", artist: "America" },
    { placement: 9, song: "I Am The Walrus", artist: "The Beatles" },
    { placement: 10, song: "Monkey Gone To Heaven", artist: "Pixies" },
    { placement: 11, song: "Dog Days Are Over", artist: "Florence + The Machine" },
    { placement: 12, song: "Nellie The Elephant", artist: "Toy Dolls" },
    { placement: 13, song: "Statdtaffe", artist: "Peter Fox" },
    { placement: 14, song: "Eisbär", artist: "Grauzone" },
    { placement: 15, song: "Elephant", artist: "Tame Impala" },
    { placement: 16, song: "Buffalo Stance", artist: "Neneh Cherry" },
    { placement: 17, song: "Eye Of The Tiger", artist: "Survivor" },
    { placement: 18, song: "Hounds Of Love", artist: "Kate Bush" },
    { placement: 19, song: "Barracuda", artist: "Heart" },
    { placement: 20, song: "Claudia Hat 'Nen Schäferhund", artist: "Die Ärzte" },
    { placement: 21, song: "Hungry Like The Wolf", artist: "Duran Duran" },
    { placement: 22, song: "Human Fly", artist: "The Cramps" },
    { placement: 23, song: "Cat People (Putting Out Fire)", artist: "David Bowie" },
    { placement: 24, song: "Bird On The Wire", artist: "Leonard Cohen" },
    { placement: 25, song: "Can Your Pussy Do The Dog?", artist: "The Cramps" },
    { placement: 26, song: "I Like Birds", artist: "Eels" },
    { placement: 27, song: "Albatros", artist: "Karat" },
    { placement: 28, song: "Meat Is Murder", artist: "The Smiths" },
    { placement: 29, song: "Die Tse Tse Fliege", artist: "Oma Hans" },
    { placement: 30, song: "White Rabbit", artist: "Jefferson Airplane" },
    { placement: 31, song: "The Lion Sleeps Tonight", artist: "The Tokens" },
    { placement: 32, song: "Walkin’ My Cat Named Dog", artist: "Norma Tanega" },
    { placement: 33, song: "Who Let The Dogs Out?", artist: "Baha Men" },
    { placement: 34, song: "I’m Like A Bird", artist: "Nelly Furtado" },
    { placement: 35, song: "Boris The Spider", artist: "The Who" },
    { placement: 36, song: "Surfin' Bird", artist: "The Trashmen" },
    { placement: 37, song: "Fly Like An Eagle", artist: "Steve Miller Band" },
    { placement: 38, song: "Hound Dog", artist: "Elvis Presley" },
    { placement: 39, song: "Katzeklo", artist: "Helge Schneider" },
    { placement: 40, song: "Die Tiere Sind Unruhig", artist: "Kante" },
    { placement: 41, song: "Stray Cat Strut", artist: "Stray Cats" },
    { placement: 42, song: "Wolf Like Me", artist: "TV On The Radio" },
    { placement: 43, song: "Crocodile Rock", artist: "Elton John" },
    { placement: 44, song: "Cats And Dogs", artist: "Gorilla Biscuits" },
    { placement: 45, song: "Endlich Einmal", artist: "Tomte" },
    { placement: 46, song: "Shock The Monkey", artist: "Peter Gabriel" },
    { placement: 47, song: "Zum Laichen Und Sterben Ziehen Die Lachse Den Fluss Hinauf", artist: "Thees Uhlmann" },
    { placement: 48, song: "Animal", artist: "Pearl Jam" },
    { placement: 49, song: "Schwan", artist: "Turbostaat" },
    { placement: 50, song: "White Bird", artist: "It`s A Beautiful Day" },
    { placement: 51, song: "Karl Der Käfer", artist: "Gänsehaut" },
    { placement: 52, song: "Little Lion Man", artist: "Mumford & Sons" },
    { placement: 53, song: "Fox On The Run", artist: "The Sweet" },
    { placement: 54, song: "Animal", artist: "Miike Snow" },
    { placement: 55, song: "Ride A White Swan", artist: "T. Rex" },
    { placement: 56, song: "Hund", artist: "Yukno" },
    { placement: 57, song: "Bird Song", artist: "Lene Lovich" },
    { placement: 58, song: "Horse And I", artist: "Bat For Lashes" },
    { placement: 59, song: "I Cut Like A Buffalo", artist: "The Dead Weather" },
    { placement: 60, song: "Brass Monkey", artist: "Beastie Boys" },
    { placement: 61, song: "Three Little Birds", artist: "Bob Marley & The Wailers" },
    { placement: 62, song: "Coyote", artist: "Joni Mitchell" },
    { placement: 63, song: "Hound Dog", artist: "Big Mama Thornton" },
    { placement: 64, song: "The Lamb Lies Down On Broadway", artist: "Genesis" },
    { placement: 65, song: "Piggies", artist: "The Beatles" },
    { placement: 66, song: "Buffalo Soldier", artist: "Bob Marley & The Wailers\n" },
    { placement: 67, song: "Land: Horses / Land Of A Thousand Dances / La Mer(de)", artist: "Patti Smith" },
    { placement: 68, song: "Eagle", artist: "ABBA" },
    { placement: 69, song: "Teach Me Tiger", artist: "April Stevens" },
    { placement: 70, song: "Atomic Dog", artist: "George Clinton" },
    { placement: 71, song: "Birds", artist: "Frida Hyvönen" },
    { placement: 72, song: "I Love My Dog", artist: "Cat Stevens" },
    { placement: 73, song: "Karma Chameleon", artist: "Culture Club" },
    { placement: 74, song: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 75, song: "Octopus‘s Garden", artist: "The Beatles" },
    { placement: 76, song: "Sheep", artist: "The Housemartins" },
    { placement: 77, song: "Do The Dog", artist: "The Specials" },
    { placement: 78, song: "The Fox In The Snow", artist: "Belle And Sebastian" },
    { placement: 79, song: "Albatross", artist: "Fleetwood Mac" },
    { placement: 80, song: "Crickets Sing For Anamaria", artist: "Marcos Valle" },
    { placement: 81, song: "N' Käfer Auf'm Blatt", artist: "Chicorée" },
    { placement: 82, song: "Mister, Would You Please Help My Pony?", artist: "Ween" },
    { placement: 83, song: "Ich Und Mein Freund Die Katze", artist: "Interzone" },
    { placement: 84, song: "Iron Lion Zion", artist: "Bob Marley" },
    { placement: 85, song: "(Let Me Be Your) Teddy Bear", artist: "Elvis Presley" },
    { placement: 86, song: "Pink Panther Theme", artist: "Henry Mancini" },
    { placement: 87, song: "Sparrow", artist: "Marvin Gaye" },
    { placement: 88, song: "The Snake", artist: "Al Wilson" },
    { placement: 89, song: "Der Letzte Kranich", artist: "Tocotronic" },
    { placement: 90, song: "Free Bird", artist: "Lynyrd Skynyrd" },
    { placement: 91, song: "Rhinoceros", artist: "The Smashing Pumpkins" },
    { placement: 92, song: "Me And My Monkey", artist: "Robbie Williams" },
    { placement: 93, song: "We Are The Pigs", artist: "Suede" },
    { placement: 94, song: "Too Many Puppies", artist: "Primus" },
    { placement: 95, song: "Sheep", artist: "Pink Floyd" },
    { placement: 96, song: "Long Snake Moan", artist: "PJ Harvey" },
    { placement: 97, song: "Lullaby", artist: "The Cure" },
    { placement: 98, song: "Pet Sematary", artist: "Ramones" },
    { placement: 99, song: "Delilah", artist: "Queen" },
    { placement: 100, song: "Anaconda", artist: "Nicki Minaj" }]
};

export const numbers: Board = {
  name: 'Magic Numbers - Die 100 besten Songs mit Zahlen im Titel',
  lines: [
    { placement: 1, song: "Song 2", artist: "Blur" },
    { placement: 2, song: "1234", artist: "Feist" },
    { placement: 3, song: "1999", artist: "Prince" },
    { placement: 4, song: "Seven Nation Army", artist: "The White Stripes" },
    { placement: 5, song: "50 Ways To Leave Your Lover", artist: "Paul Simon" },
    { placement: 6, song: "One", artist: "U2" },
    { placement: 7, song: "Disco 2000", artist: "Pulp" },
    { placement: 8, song: "1979", artist: "The Smashing Pumpkins" },
    { placement: 9, song: "99 Problems", artist: "Jay-Z" },
    { placement: 10, song: "One", artist: "Metallica" },
    { placement: 11, song: "99 Luftballons", artist: "Nena" },
    { placement: 12, song: "Edge Of Seventeen", artist: "Stevie Nicks" },
    { placement: 13, song: "48 Crash", artist: "Suzi Quatro" },
    { placement: 14, song: "54-46 Was My Number", artist: "Toots & The Maytals" },
    { placement: 15, song: "1969", artist: "The Stooges" },
    { placement: 16, song: "2000 Light Years From Home", artist: "The Rolling Stones" },
    { placement: 17, song: "10.15 Saturday Night", artist: "The Cure" },
    { placement: 18, song: "96 Tears", artist: "? & The Mysterians" },
    { placement: 19, song: "Eight Days A Week", artist: "The Beatles" },
    { placement: 20, song: "20th Century Boy", artist: "T. Rex" },
    { placement: 21, song: "100%", artist: "Sonic Youth" },
    { placement: 22, song: "Thirteen", artist: "Big Star" },
    { placement: 23, song: "2-4-6-8 Motorway", artist: "Tom Robinson Band" },
    { placement: 24, song: "6060-842", artist: "The B-52's" },
    { placement: 25, song: "Nummern", artist: "Kraftwerk" },
    { placement: 26, song: "Five Years", artist: "David Bowie" },
    { placement: 27, song: "Nothing Compares 2 U", artist: "Sinéad O' Connor" },
    { placement: 28, song: "Eight Miles High\n", artist: "The Byrds\n" },
    { placement: 29, song: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
    { placement: 30, song: "12:15", artist: "The Strokes" },
    { placement: 31, song: "The Magic Number", artist: "De La Soul" },
    { placement: 32, song: "If 6 Was 9", artist: "The Jimi Hendrix Experience" },
    { placement: 33, song: "7 Seconds", artist: "Youssou N`Dour & Neneh Cherry" },
    { placement: 34, song: "12XU", artist: "Wire" },
    { placement: 35, song: "When I'm Sixty-Four", artist: "The Beatles" },
    { placement: 36, song: "One", artist: "Aimee Mann" },
    { placement: 37, song: "The Four Horsemen", artist: "Aphrodite`s Child" },
    { placement: 38, song: "The Number Of The Beast", artist: "Iron Maiden" },
    { placement: 39, song: "2000 Mädchen", artist: "Die Ärzte" },
    { placement: 40, song: "Three Is A Magic Number", artist: "Bob Dorough" },
    { placement: 41, song: "48 Stunden", artist: "Kettcar" },
    { placement: 42, song: "19", artist: "Paul Hardcastle" },
    { placement: 43, song: "Four Women", artist: "Nina Simone" },
    { placement: 44, song: "1901", artist: "Phoenix" },
    { placement: 45, song: "Little 15", artist: "Depeche Mode" },
    { placement: 46, song: "Little Numbers", artist: "Boy" },
    { placement: 47, song: "9 To 5", artist: "Dolly Parton" },
    { placement: 48, song: "911 Is A Joke", artist: "Public Enemy" },
    { placement: 49, song: "Waltz #2 (XO)", artist: "Elliott Smith" },
    { placement: 50, song: "Thirteen", artist: "Jingo De Lunch" },
    { placement: 51, song: "Highway 61 Revisited", artist: "Bob Dylan" },
    { placement: 52, song: "50ft Queenie", artist: "PJ Harvey" },
    { placement: 53, song: "One", artist: "Harry Nilsson" },
    { placement: 54, song: "Tausend Tränen Tief", artist: "Blumfeld" },
    { placement: 55, song: "21st Century (Digital Boy)", artist: "Bad Religion" },
    { placement: 56, song: "Seventeen", artist: "Sharon Van Etten" },
    { placement: 57, song: "2 Oder 3 Dinge, Die Ich Von Dir Weiß", artist: "Blumfeld" },
    { placement: 58, song: "Zehn", artist: "Farin Urlaub Racing Team" },
    { placement: 59, song: "Eins Und Eins, Das Macht Zwei", artist: "Hildegard Knef" },
    { placement: 60, song: "Paris 1919", artist: "John Cale" },
    { placement: 61, song: "51st State", artist: "New Model Army" },
    { placement: 62, song: "Two Weeks", artist: "FKA Twigs" },
    { placement: 63, song: "Five To One", artist: "The Doors" },
    { placement: 64, song: "52 Girls", artist: "The B-52's" },
    { placement: 65, song: "Nr. 48", artist: "Engerling" },
    { placement: 66, song: "One More Time", artist: "Daft Punk" },
    { placement: 67, song: "25 Or 6 To 4", artist: "Chicago" },
    { placement: 68, song: "54/40 Or Fight", artist: "Dead Moon" },
    { placement: 69, song: "The Magnificent Seven", artist: "The Clash" },
    { placement: 70, song: "Chelsea Hotel #2", artist: "Leonard Cohen" },
    { placement: 71, song: "Take Five", artist: "Dave Brubeck Quartet" },
    { placement: 72, song: "Revolution 9", artist: "The Beatles" },
    { placement: 73, song: "One", artist: "Three Dog Night" },
    { placement: 74, song: "Forty Six & 2", artist: "Tool" },
    { placement: 75, song: "1/2 Lovesong", artist: "Die Ärzte" },
    { placement: 76, song: "Seventeen Seconds", artist: "The Cure" },
    { placement: 77, song: "Thirteen\n", artist: "Johnny Cash" },
    { placement: 78, song: "1,2,3,4", artist: "Wanda" },
    { placement: 79, song: "2 Become 1", artist: "Spice Girls" },
    { placement: 80, song: "3 Millionen", artist: "Bosse" },
    { placement: 81, song: "33 \"GOD\"", artist: "Bon Iver" },
    { placement: 82, song: "1000 Und 1 Nacht (Zoom!)", artist: "Klaus Lage Band" },
    { placement: 83, song: "Summer Of `69", artist: "Bryan Adams" },
    { placement: 84, song: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, song: "Route 66", artist: "Chuck Berry" },
    { placement: 86, song: "9010", artist: "Kummer" },
    { placement: 87, song: "23", artist: "Jimmy Eat World" },
    { placement: 88, song: "I-94", artist: "Radio Birdman" },
    { placement: 89, song: "Chant No. 1 (I Don't Need This Pressure On)", artist: "Spandau Ballet" },
    { placement: 90, song: "Mit 66 Jahren", artist: "Udo Jürgens" },
    { placement: 91, song: "Perfect 10", artist: "The Beautiful South" },
    { placement: 92, song: "Nineteen Hunderd And Eighty Five", artist: "Paul McCartney & Wings" },
    { placement: 93, song: "3 MC's And 1 DJ", artist: "Beastie Boys" },
    { placement: 94, song: "Links 2-3-4", artist: "Rammstein" },
    { placement: 95, song: "One", artist: "Johnny Cash" },
    { placement: 96, song: "Care Of Cell 44", artist: "The Zombies" },
    { placement: 97, song: "1-2 5", artist: "The Haunted" },
    { placement: 98, song: "19th Nervous Breakdown", artist: "The Rolling Stones" },
    { placement: 99, song: "'39", artist: "Queen" },
    { placement: 100, song: "4 Degrees", artist: "Anohni" }]
};

export const family: Board = {
  name: 'We Are Family - Die 100 besten Familienlieder',
  lines: [
    { placement: 1, song: "Family Affair", artist: "Sly & The Family Stone" },
    { placement: 2, song: "Father And Son", artist: "Cat Stevens" },
    { placement: 3, song: "We Are Family", artist: "Sister Sledge" },
    { placement: 4, song: "Mother", artist: "Danzig" },
    { placement: 5, song: "We're A Happy Family", artist: "Ramones" },
    { placement: 6, song: "Mother", artist: "John Lennon & Plastic Ono Band" },
    { placement: 7, song: "Sisters Are Doin' It For Themselves", artist: "Eurythmics & Aretha Franklin" },
    { placement: 8, song: "Papa Was A Rollin' Stone", artist: "The Temptations" },
    { placement: 9, song: "Family Affair", artist: "Mary J. Blige" },
    { placement: 10, song: "Father Figure", artist: "George Michael" },
    { placement: 11, song: "My Little Brother", artist: "Art Brut" },
    { placement: 12, song: "Grandma's Hands", artist: "Bill Withers" },
    { placement: 13, song: "Ode To My Family", artist: "The Cranberries" },
    { placement: 14, song: "Neue Zähne Für Meinen Bruder Und Mich", artist: "Superpunk" },
    { placement: 15, song: "You Are My Sister", artist: "Antony And The Johnsons feat. Boy George" },
    { placement: 16, song: "Little Sister", artist: "Queens Of The Stone Age" },
    { placement: 17, song: "Family Portrait", artist: "Pink" },
    { placement: 18, song: "Geschwisterliebe", artist: "Die Ärzte" },
    { placement: 19, song: "My Father's Eyes", artist: "Eric Clapton" },
    { placement: 20, song: "Oft Gefragt", artist: "AnnenMayKantereit" },
    { placement: 21, song: "My Perfect Cousin", artist: "The Undertones" },
    { placement: 22, song: "Mother", artist: "IDLES" },
    { placement: 23, song: "Brothers In Arms", artist: "Dire Straits" },
    { placement: 24, song: "Hey Jude", artist: "The Beatles" },
    { placement: 25, song: "Bologna", artist: "Wanda" },
    { placement: 26, song: "Mama", artist: "Genesis" },
    { placement: 27, song: "Teach Your Children", artist: "Crosby, Stills, Nash & Young" },
    { placement: 28, song: "Isn't She Lovely", artist: "Stevie Wonder" },
    { placement: 29, song: "Oh, Sister", artist: "Bob Dylan" },
    { placement: 30, song: "He Ain't Heavy, He's My Brother", artist: "The Hollies" },
    { placement: 31, song: "Sister", artist: "The Black Keys" },
    { placement: 32, song: "Tears In Heaven", artist: "Eric Clapton" },
    { placement: 33, song: "Bro Hymn", artist: "Pennywise" },
    { placement: 34, song: "Papa Don't Preach", artist: "Madonna" },
    { placement: 35, song: "Family Man", artist: "Fleetwood Mac" },
    { placement: 36, song: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 37, song: "Daughter", artist: "Pearl Jam" },
    { placement: 38, song: "Bridge Over Troubled Water", artist: "Simon & Garfunkel" },
    { placement: 39, song: "Mother And Child Reunion", artist: "Paul Simon" },
    { placement: 40, song: "(We Don't Need This) Fascist Groove Thang", artist: "Heaven 17" },
    { placement: 41, song: "Shakespeare's Sister", artist: "The Smiths" },
    { placement: 42, song: "Brother Father Mother Sister", artist: "Tim Maia" },
    { placement: 43, song: "Hey, Ma", artist: "Bon Iver" },
    { placement: 44, song: "The Mother We Share", artist: "Chvrches" },
    { placement: 45, song: "Oh, Mama", artist: "The Düsseldorf Düsterboys" },
    { placement: 46, song: "What's Happening Brother", artist: "Marvin Gaye" },
    { placement: 47, song: "Mutter", artist: "Rammstein" },
    { placement: 48, song: "Mother", artist: "Pink Floyd" },
    { placement: 49, song: "Kooks", artist: "David Bowie" },
    { placement: 50, song: "Gone Daddy Gone", artist: "Violent Femmes" },
    { placement: 51, song: "She's Leaving Home", artist: "The Beatles" },
    { placement: 52, song: "Born To A Family", artist: "The Go-Betweens" },
    { placement: 53, song: "Ich Will Nicht Werden, Was Mein Alter Ist", artist: "Ton Steine Scherben" },
    { placement: 54, song: "Song For Our Daughter", artist: "Laura Marling" },
    { placement: 55, song: "Bloody Mother Fucking Asshole", artist: "Martha Wainwright" },
    { placement: 56, song: "Sisters Of Mercy", artist: "Leonard Cohen" },
    { placement: 57, song: "No Son Of Mine", artist: "Genesis" },
    { placement: 58, song: "Junge", artist: "Die Ärzte" },
    { placement: 59, song: "Our House", artist: "Madness" },
    { placement: 60, song: "Mama Said Knock You Out", artist: "LL Cool J" },
    { placement: 61, song: "I'm My Own Grandpa", artist: "Lonzo & Oscar" },
    { placement: 62, song: "The Exchange", artist: "Torres" },
    { placement: 63, song: "Hey Brother", artist: "Avicii" },
    { placement: 64, song: "Dear Mama", artist: "2Pac" },
    { placement: 65, song: "The Good Son", artist: "Nick Cave & The Bad Seeds" },
    { placement: 66, song: "Mommy's Little Monster", artist: "Social Distortion" },
    { placement: 67, song: "Oh Father", artist: "Madonna" },
    { placement: 68, song: "Julia", artist: "The Beatles" },
    { placement: 69, song: "It's Alright Ma (I'm Only Bleeding)", artist: "Bob Dylan" },
    { placement: 70, song: "Sister Moon", artist: "Sting" },
    { placement: 71, song: "Puppe", artist: "Rammstein" },
    { placement: 72, song: "Cat's In The Cradle", artist: "Harry Chapin" },
    { placement: 73, song: "Mama", artist: "Spice Girls" },
    { placement: 74, song: "It's A Shame (My Sister)", artist: "Monie Love" },
    { placement: 75, song: "Daddy", artist: "Coldplay" },
    { placement: 76, song: "I Can Never Go Home Anymore", artist: "The Shangri-Las" },
    { placement: 77, song: "Unknown Brother", artist: "The Black Keys" },
    { placement: 78, song: "Mama", artist: "My Chemical Romance" },
    { placement: 79, song: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 80, song: "Papaoutai", artist: "Stromae" },
    { placement: 81, song: "The Addams Family Theme", artist: "Vic Mizzy & His Orchestra" },
    { placement: 82, song: "Papa Won't Leave You, Henry", artist: "Nick Cave & The Bad Seeds" },
    { placement: 83, song: "My Son Calls Another Man Daddy", artist: "Hank Williams" },
    { placement: 84, song: "Ich Heirate Eine Familie", artist: "Tocotronic" },
    { placement: 85, song: "Your Mother Should Know", artist: "The Beatles" },
    { placement: 86, song: "I'll Be There", artist: "The Jackson 5" },
    { placement: 87, song: "Mother Stands For Comfort", artist: "Kate Bush" },
    { placement: 88, song: "Vater", artist: "Soap&Skin" },
    { placement: 89, song: "Meine Schwester", artist: "Tocotronic" },
    { placement: 90, song: "Dance Little Sister", artist: "Terence Trent D'Arby" },
    { placement: 91, song: "Brother And Sister", artist: "The Gun Club" },
    { placement: 92, song: "Death With Dignity", artist: "Sufjan Stevens" },
    { placement: 93, song: "Lonesome Valley", artist: "Bill Callahan" },
    { placement: 94, song: "Brother Louie", artist: "Modern Talking" },
    { placement: 95, song: "Say It Ain't So", artist: "Weezer" },
    { placement: 96, song: "Nur Zu Besuch", artist: "Die Toten Hosen" },
    { placement: 97, song: "Randale", artist: "Kraftklub" },
    { placement: 98, song: "Kids", artist: "MGMT" },
    { placement: 99, song: "Niemand Wie Ihr", artist: "Feine Sahne Fischfilet" },
    { placement: 100, song: "Sister Surround", artist: "The Soundtrack Of Our Lives" }]
};

export const drugs: Board = {
  name: 'Flying High - Die 100 besten Drogen-Lieder',
  lines: [
    { placement: 1, song: "Heroin", artist: "The Velvet Underground" },
    { placement: 2, song: "White Rabbit", artist: "Jefferson Airplaine" },
    { placement: 3, song: "The Drugs Don't Work", artist: "The Verve" },
    { placement: 4, song: "Rehab", artist: "Amy Winehouse" },
    { placement: 5, song: "I´m Waiting For The Man", artist: "The Velvet Undergound" },
    { placement: 6, song: "Lucy In The Sky With Diamonds", artist: "The Beatles" },
    { placement: 7, song: "The Needle And The Damage Done", artist: "Neil Young" },
    { placement: 8, song: "Feel Good Hit Of The Summer", artist: "Queens Of The Stone Age" },
    { placement: 9, song: "Purple Haze", artist: "The Jimi Hendrix Experience" },
    { placement: 10, song: "Under The Bridge", artist: "Red Hot Chili Peppers" },
    { placement: 11, song: "Golden Brown", artist: "The Stranglers" },
    { placement: 12, song: "Cocaine", artist: "J. J. Cale" },
    { placement: 13, song: "Drogen Nehmen Und Rumfahren", artist: "Die Zukunft" },
    { placement: 14, song: "Am Tag, Als Conny Kramer Starb", artist: "Juliane Werding" },
    { placement: 15, song: "Needle In The Hay", artist: "Elliott Smith" },
    { placement: 16, song: "White Lines (Don't Don't Do It)", artist: "Grandmaster Flash & Melle Mel" },
    { placement: 17, song: "Pusherman", artist: "Curtis Mayfield" },
    { placement: 18, song: "Cold Turkey", artist: "John Lennon & Plastic Ono Band" },
    { placement: 19, song: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 20, song: "Comfortably Numb", artist: "Pink Floyd" },
    { placement: 21, song: "Eight Miles High", artist: "The Byrds" },
    { placement: 22, song: "Alkohol", artist: "Herbert Grönemeyer" },
    { placement: 23, song: "Lithium", artist: "Nirvana" },
    { placement: 24, song: "True Faith", artist: "New Order" },
    { placement: 25, song: "You Need The Drugs", artist: "Westbam feat. Richard Butler" },
    { placement: 26, song: "Gold Dust Woman", artist: "Fleetwood Mac" },
    { placement: 27, song: "Beetlebum", artist: "Blur" },
    { placement: 28, song: "Can't Feel My Face", artist: "The Weeknd" },
    { placement: 29, song: "Because I Got High", artist: "Afroman" },
    { placement: 30, song: "Hits From The Bong", artist: "Cypress Hill" },
    { placement: 31, song: "I Wanna Be Sedated", artist: "Ramones" },
    { placement: 32, song: "Cocaine In My Brain", artist: "Dillinger" },
    { placement: 33, song: "Where Is My Mind?", artist: "Pixies" },
    { placement: 34, song: "Higher Than The Sun", artist: "Primal Scream" },
    { placement: 35, song: "Sister Morphine", artist: "Marianne Faithfull" },
    { placement: 36, song: "Sorted For E's And Wizz", artist: "Pulp" },
    { placement: 37, song: "Champagne Supernova", artist: "Oasis" },
    { placement: 38, song: "Insane In The Brain", artist: "Cypress Hill" },
    { placement: 39, song: "Perfect Day", artist: "Lou Reed" },
    { placement: 40, song: "Mother I’ve Taken LSD", artist: "The Flaming Lips" },
    { placement: 41, song: "Straight Edge", artist: "Minor Threat" },
    { placement: 42, song: "Sex & Drugs & Rock & Roll", artist: "Ian Dury" },
    { placement: 43, song: "Hurt", artist: "Nine Inch Nails" },
    { placement: 44, song: "Mary Jane's Last Dance", artist: "Tom Petty & The Heartbreakers" },
    { placement: 45, song: "My Friend Jack", artist: "The Smoke" },
    { placement: 46, song: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 47, song: "Ebeneezer Goode", artist: "The Shamen" },
    { placement: 48, song: "Never Let Me Down Again", artist: "Depeche Mode" },
    { placement: 49, song: "Ganz Wien", artist: "Falco" },
    { placement: 50, song: "3 Tage Wach", artist: "Lützenkirchen" },
    { placement: 51, song: "Master Of Puppets", artist: "Metallica" },
    { placement: 52, song: "Bianco", artist: "Yung Hurn & RIN" },
    { placement: 53, song: "Cigarettes & Alcohol", artist: "Oasis" },
    { placement: 54, song: "Just One Fix", artist: "Ministry" },
    { placement: 55, song: "The Pusher", artist: "Steppenwolf" },
    { placement: 56, song: "Drugs", artist: "Upsahl" },
    { placement: 57, song: "Mutter, Der Mann Mit Dem Koks Ist Da", artist: "Falco" },
    { placement: 58, song: "Special K", artist: "Placebo" },
    { placement: 59, song: "Swimming Pools (Drank)", artist: "Kendrick Lamar" },
    { placement: 60, song: "Heute Schütte Ich Mich Zu", artist: "Karl Dall" },
    { placement: 61, song: "Eight Miles High", artist: "Hüsker Dü" },
    { placement: 62, song: "High By The Beach", artist: "Lana Del Rey" },
    { placement: 63, song: "My Drug Buddy", artist: "The Lemonheads" },
    { placement: 64, song: "Brown Sugar", artist: "The Rolling Stones" },
    { placement: 65, song: "Hurt", artist: "Johnny Cash" },
    { placement: 66, song: "White Punks On Dope", artist: "The Tubes" },
    { placement: 67, song: "Cola-Wodka", artist: "Holger Biege" },
    { placement: 68, song: "Alabama Song (Whisky Bar)", artist: "The Doors" },
    { placement: 69, song: "Why’d You Only Call Me When You’re High?", artist: "Arctic Monkeys" },
    { placement: 70, song: "I'm Your Pusher", artist: "Ice-T" },
    { placement: 71, song: "Hash Pipe", artist: "Weezer" },
    { placement: 72, song: "Brown Sugar", artist: "D'Angelo" },
    { placement: 73, song: "Tag Am Meer", artist: "Die Fantastischen Vier" },
    { placement: 74, song: "Sugar Man", artist: "Rodriguez" },
    { placement: 75, song: "Mix Mir Einen Drink", artist: "Feeling B" },
    { placement: 76, song: "Mary Jane", artist: "Rick James" },
    { placement: 77, song: "Bongzimmer", artist: "SXTN" },
    { placement: 78, song: "Crystal Meth In Brandenburg", artist: "Grim104" },
    { placement: 79, song: "Hotel California", artist: "Eagles" },
    { placement: 80, song: "Cocaine", artist: "Eric Clapton" },
    { placement: 81, song: "Willst Du", artist: "Alligatoah" },
    { placement: 82, song: "Needle Of Death", artist: "Bert Jansch" },
    { placement: 83, song: "Kokain", artist: "Hannes Wader" },
    { placement: 84, song: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, song: "Rainy Day Women #12 & 35", artist: "Bob Dylan" },
    { placement: 86, song: "Karlsquell", artist: "Slime" },
    { placement: 87, song: "Xanny", artist: "Billie Eilish" },
    { placement: 88, song: "Ashes To Ashes", artist: "David Bowie" },
    { placement: 89, song: "White Horse", artist: "Laid Back" },
    { placement: 90, song: "We Are All On Drugs", artist: "Weezer" },
    { placement: 91, song: "Not If You Were The Last Junkie On Earth", artist: "The Dandy Warhols" },
    { placement: 92, song: "Pass That Dutch", artist: "Missy Elliott" },
    { placement: 93, song: "Lost", artist: "Frank Ocean" },
    { placement: 94, song: "Blinded By The Lights", artist: "The Streets" },
    { placement: 95, song: "Sam Stone", artist: "John Prine" },
    { placement: 96, song: "Nicotine", artist: "Chef'Special" },
    { placement: 97, song: "Novacane", artist: "Frank Ocean" },
    { placement: 98, song: "Strychnine", artist: "The Sonics" },
    { placement: 99, song: "King Heroin", artist: "James Brown" },
    { placement: 100, song: "Zeit Steht", artist: "Trettmann feat. Alli Neumann" },
  ]
};
